### ISSUE TITLE
Suggestion to Automate Syncing GitHub Repository with Wiki

### ISSUE THREAD

**Issue by Honoka55** [XYY-huijiwiki/XYY-huijiwiki-components#9]
I noticed that there is no mechanism to automatically sync the contents of the GitHub repository with the wiki. I believe that having a bot that can automate this task will significantly improve the efficiency and accuracy of keeping the two platforms in sync.

I would like to suggest creating another bot account (how about we call it iWeslie?) to perform this task, and I would be happy to help with the implementation if needed. [This](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#编译流程) may be referred for the compilation process. I believe that this feature will greatly benefit the wiki.

**Comment by XiaoSong-CPE** [comment]
好的

**Comment by XiaoSong-CPE** [comment]
I suppose the new robot account may have no permission to edit HTML pages. In fact, functions like [上传特殊文件](https://xyy.huijiwiki.com/wiki/Project:上传特殊文件) can get `.html` file (as well as `.js` and `.css` etc.) from [jsDelivr](https://www.jsdelivr.com), which syncs files in Github and the network condition in mainland China is much better. Build-step VUE project like base64-file-uploader is required, to which migrate projects such as json-editor is not difficult. Before every commit, run `npm run build` and the files needed by XYY huijiwiki will present in `xyy` folder. Names of them are fixed so jsDelivr will sync those files every 7 days, in another words, files are synced to XYY huijiwiki.

**Comment by XiaoSong-CPE** [comment]
I suppose the new robot account may have no permission to edit HTML pages. In fact, functions like [上传特殊文件](https://xyy.huijiwiki.com/wiki/Project:上传特殊文件) can get `.html` file (as well as `.js` and `.css` etc.) from [jsDelivr](https://www.jsdelivr.com), which syncs files in Github and the network condition in mainland China is much better. Build-step VUE project like base64-file-uploader is required, to which migrate projects such as json-editor is not difficult. Before every commit, run `npm run build` and the files needed by XYY huijiwiki will present in `xyy` folder. Names of them are fixed so jsDelivr will sync those files every 7 days, in another words, files are synced to XYY huijiwiki.
